language: perl

perl:
    - "5.10"

env:
    PATH=~/.rakudobrew/bin:$PATH

install:
    - git clone https://github.com/tadzik/rakudobrew ~/.rakudobrew
    - echo $PATH
    - rakudobrew build moar
    - rakudobrew build-panda
    - panda install IO::Capture::Simple

script:
    - make test
